# Generated by Django 3.0.3 on 2020-03-24 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('year', 'module_id', 'semester')},
        ),
    ]
