# Generated by Django 3.0.3 on 2020-03-20 05:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2000)),
                ('semester', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('module_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('p_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Module')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Professor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.User')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='prof',
            field=models.ManyToManyField(to='rating.Professor'),
        ),
    ]
