# Generated by Django 3.0.4 on 2020-03-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='professors',
            name='id',
        ),
        migrations.AlterField(
            model_name='professors',
            name='prof_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
