# Generated by Django 3.0.4 on 2020-03-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20200306_0344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
        migrations.RenameModel(
            old_name='Professors',
            new_name='Professor',
        ),
    ]
