# Generated by Django 3.0.4 on 2020-03-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20200306_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
