# Generated by Django 3.0.4 on 2020-03-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='prof',
            field=models.ManyToManyField(to='rating.Professor'),
        ),
    ]
