# Generated by Django 3.0.4 on 2020-03-06 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_module_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Module')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Professor')),
            ],
        ),
    ]
